### ISSUE TITLE
Resolve %%% conflict with ScalaJS

### ISSUE THREAD

**Issue by briantopping** [mdedetrich/sbt-bower#6]
```%%%``` is also in use by ScalaJS. Even though they came later, my sense is they are going to prevail.

Any thoughts on resolving this? ```%^4```?

**Comment by mdedetrich** [comment]
I may have a look into this, but for the near future, it appears that I will be using web-jars instead of sbt-bower, since web-jars now have automatic packaging for bower packages (i.e. have a look at http://www.webjars.org/)

If this is still a significant issue, let me know and I will fix it

**Comment by briantopping** [comment]
Sure, makes sense. I haven't had a lot of time for front end dev lately, so apologies for the delay to get back to you on this. I'll check web-jars out, thanks for the link!
